name: React CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🧹 Run Lint
      run: |
        npm install
        npm run lint

    - name: 🔐 Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🛠️ Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .

    - name: 📦 Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
